### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ChrisHffm** [emvivre/quake-3-server-list#1]
![image](https://cloud.githubusercontent.com/assets/19880451/16716064/c0262092-46f1-11e6-82dd-1913021a2e98.png) python 3.5.1
Can i contact you please my skype is disownedx

**Comment by emvivre** [comment]
Thank you for your feedback. Indeed the code was not runnable under python 3. It should be fixed now. Try to run it again.

**Comment by ChrisHffm** [comment]
Thanks it work now :-)
