### ISSUE TITLE
Can you add more features ?

### ISSUE THREAD

**Issue by ChrisHffm** [emvivre/quake-3-server-list#2]
Hi, i see you are good in Python, can you add:
Name**/**Gametype**/**Map**/**Clients (Max)**/**IP

I know you can use
hostname/gametype/mapname/clients(sv_maxclients)
It will be awesome if you make that O_O, and i have a question it's possible to put the result into a php file ?

**Comment by emvivre** [comment]
I add these features in the code. You can get the status of a server by typping the following command:
`q3_list.py <SERVER>:<PORT>`

**Comment by ChrisHffm** [comment]
Oh thanks for this amazing work !
